### ISSUE TITLE
handle: error running event hook for S_LOGIN<event>

### ISSUE THREAD

**Issue by FrankMora** [Tera-Shiraneko/consumable-notifier#1]
[13:33:30.321] [dispatch] [tera-game-state] handle: error running event hook for S_LOGIN<event>
hook: (anonymous) in tera-game-state
error: Cannot mix BigInt and other types, use explicit conversions
    at new Timeout (internal/timers.js:159:3)
    at setInterval (timers.js:189:19)
    at electron/js2c/browser_init.js:241:392
    at Proxy.setInterval (G:\Games\TeraToolbox\bin\mod.js:62:20)
    **at start_searching (G:\Games\TeraToolbox\mods\consumable-notifier-master\index.js:114:32)**
    at NetworkMod.<anonymous> (G:\Games\TeraToolbox\mods\consumable-notifier-master\index.js:101:9)
    at NetworkMod.emit (events.js:327:22)
    at NetworkMod.setState (G:\Games\TeraToolbox\mods\tera-game-state\index.js:165:46)
    at Object.callback (G:\Games\TeraToolbox\mods\tera-game-state\index.js:143:88)

**Comment by Tera-Shiraneko** [comment]
Will fix it soon. Updated it too early as used feature just works in beta branch.

**Comment by Tera-Shiraneko** [comment]
Try again. Issue should be fixed now. @FrankMora
